<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AboutUs.aspx.cs" Inherits="AboutUs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <div class="innerContent" style="padding-top:0px;">
        <div class="about">
            <h1>About Us</h1>
            <br />
            <p><span></span><strong>Art Gallery</strong> stems from an idea by Elio d’Anna that establishes the principles and values of the cultural project forming the “Art Foundation”. Philosopher, businessman, and successful author of several literary works released around the world, such as The School of Gods and The Technology of the Dreamer, Elio d’Anna inspires and supports international artistic activities by determining the guidelines for the selection and promotion of the artists chosen. The artistic direction of the gallery is entrusted to Antonio Budetta, whose active research is aimed mainly at promoting new opportunities for current collecting.</p>
        <br />
            <p><span></span><strong>Art Gallery</strong> opened in 2007 in Pietrasanta, a Tuscan town famous for its marble and bronze processing; it is one of the residences chosen by the greatest ancient and contemporary sculptors. The spirit of this place, deeply linked to the material, leaves an enduring mark in the choice of the artists represented.  The gallery moved its main location to Florence in 2009, to a magical place only a few steps from Ponte Vecchio: an ancient courtyard with a botanical garden dating back to 1534. Here, the antique tropical garden leads to the modern early 20th century exhibition space, allowing the gallery to settle into the center of the “Renaissance” city and its memories, creating a link between historical and contemporary times.</p>
         <br />
            <p><span></span>The continuous international research occurring for almost ten years in Florentine territory has brought solo exhibitions of American artists such as Carole Feuerman and Roxan Lowitt, and Chinese artists such as Zhuang Hong Yi and Sheng Qi. The three shows by Hassan Hajjaj, Omar Iman, and Tanya Habjouqa, gave particular attention to the contemporary world of the Middle East. For the first time in Italy two of the most important Turkish artists, Burhan Dogancay and Irfan Önürmen, exhibited their artworks. In addition to representing international artists, the gallery dedicates ample space for the promotion of Italian artists both abroad and in the Florentine headquarters, giving a strong focus to young emerging talent.</p>
        <br />
            <p><span></span>In 2016, <strong>Art Gallery</strong> opened its second exhibition site in a prestigious and elegant building in Mayfair in the heart of London, near the Royal Academy of Arts and the center of today’s new contemporary art market. The centrality and beauty of the headquarters in the English capital took on the Turkish artist Irfan Önürmen, who exhibited his artwork for the first time on the English territory.</p>
            <br />
            <p><span></span>The third venue of <strong>Art Gallery</strong> was inaugurated in February 2018 in Istanbul, close to Istanbul Modern, the Museum of Modern and Contemporary Art, and Karakoy, a district growing in art and culture. The choice to open in the Turkish artistic capital follows from participating in the Contemporary Istanbul Art Fair, where it has attracted the attention of the most important collectors and curators in the last five years.</p>
            <br />
            <p><span></span>The gallery actively participates in various international fairs and exhibitions, collaborating with public museums, public and private entities, foundations, and embassies. The gallery’s institutional projects include Icastica at the first biennial of contemporary art in Arezzo at National Museum of Medieval and Modern Art in 2013; the exhibition Le Bagnanti (The Bathers) in 2015, which included bathing sculptures and posters by Carole Feuerman in Toiletpaper in collaboration with the Municipal Gallery of Modern and Contemporary Art of Rimini; in 2016, the group exhibition Perditiva, in collaboration with the Design Biennale and the Cultural Department of Rimini; in 2016 the personal exhibition by Carole Feuerman Lo Sport del Bellessere (The Sport of Beauty-Being) at the Museo Civico of Palazzo Elti in Gemona del Friuli; the participation in the 56th Venice Biennale with the collateral collective exhibition Personal Structures-Crossing Borders, where Carole Feuerman and Andrea Guastavino’s artworks were exhibited; the Timelessness exhibition, presented both in Florence and in London, in collaboration with Giorgio Baratti Antique Gallery, highlights the inseparability between past and present, combining 16th and 17th century painting with contemporary artworks.</p>
            <br />
        </div>
    </div>
</asp:Content>

